services:
  - type: web
    name: centre-mandela
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ./data/database.sqlite
      - key: VITE_API_URL
        value: /api
    buildFilter:
      paths:
        - client/**
        - server/**
        - shared/**
